### ISSUE TITLE
Use Subsocial logo on Settings page of Apps (endpoint dropdown)

### ISSUE THREAD

**Issue by subsocialdev** [dappforce/dappforce-subsocial-apps#58]
Replace Substrate logo w/ Subsocial logo.

![image](https://user-images.githubusercontent.com/62490051/84769330-54e33b80-afde-11ea-8aac-eb34a6d10f38.png)

**Comment by siman** [comment]
Done:
![image](https://user-images.githubusercontent.com/153928/91021138-019ff180-e5fc-11ea-9a75-f8d0a45d6bac.png)
